# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'azure DevOps web-app project'
    repository: 'chyjuls/web-delivery:v1'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'kubernetes_deploy'
    azureResourceGroup: 'networking-resource-group>'
    kubernetesCluster: 'terraform-aks-cluster'
    command: 'apply'
    arguments: '-f $(System.DefaultWorkingDirectory)/aks-terraform/application-manifest.yaml'

